language: python

sudo: false

services:
  - redis

python:
  - "3.8"

before_install:
  - pip install coverage requests-mock

install:
  - pip install -r requirements.txt

env:
  - REDIS=localhost

script:
  - cd tests
  - coverage run test_fansub.py

after_success:
  - bash <(curl -s https://codecov.io/bash)