language: python

services:
  - redis
python:
  - "3.7"
  - "3.8"

install:
  - pip install -r requirements.txt

env:
  - REDIS=locahost

script:
  - cd tests && python /build_test.py
  - python tests/turing_test.py
