name: Release binary
on:
  push:
    tags:
      - "*"

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Golang
        uses: actions/setup-go@v2
        with:
          go-version: '1.19'

      - name: Build binary
        run: |
          make current
          mv yyetsweb/yyetsweb yyetsweb-linux

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: yyetsweb-linux
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


  windows:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Golang
        uses: actions/setup-go@v2
        with:
          go-version: '1.19'

      - name: Build binary
        run: |
          make current
          mv yyetsweb/yyetsweb.exe yyetsweb-windows.exe

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: yyetsweb-windows.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  macos:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Golang
        uses: actions/setup-go@v2
        with:
          go-version: '1.19'

      - name: Build binary
        run: |
          make current
          mv yyetsweb/yyetsweb yyetsweb-darwin

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: yyetsweb-darwin
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
